### ISSUE TITLE
Revisar sobre posicion de texto en vista modificar /clientes/proveedores

### ISSUE THREAD

**Issue by armandie2013** [FullStackEggDRoa/proyecto_003-GF#121]
Se sugiere usar th:value en lugar th:text. Mirar ejemplo, siguiente:

```
<div class="inputContainer">
<input type="number" class="input" **th:text=**"${Cliente.dni.numero}" name="dni" 
</div>
```

**Comment by dnroar** [comment]
Si este efecto tenemos de forma visual.

![Screen Shot 2023-09-23 at 12 03 28](https://github.com/FullStackEggDRoa/proyecto_003-GF/assets/119772142/ed29ac2a-08ec-498c-a3df-1abb9432d824)

Por favor @d4ivc hacer seguimiento. gracias.

**Comment by LucasGes** [comment]
Se modificaron los th.text, de todos los formularios, por th.value.

Para quitar el control de numeracion se sugiere utilizar en CSS las siguientes lineas:

input[type="number"]::-webkit-inner-spin-button,
input[type="number"]::-webkit-outer-spin-button {
    -webkit-appearance: none;
    appearance: none;
    margin: 0;
}
