### ISSUE TITLE
Doble Avatar en Icono de Perfil - FrontEnd

### ISSUE THREAD

**Issue by d4ivc** [FullStackEggDRoa/proyecto_003-GF#124]
Una vez modificados los datos aparecen 2 marcianitos en vez de 1, entiendo que aparece el viejo (que se cambio) y el nuevo (el actualizado).

**Comment by dnroar** [comment]
Se tuvo que usar redirect:/usuario/sesion, para forzar que se carguen las variables necesarias para cargar Perfiles y Contenidos.
