### ISSUE TITLE
Formulario Registrar Cliente y Proveedor - FrontEnd

### ISSUE THREAD

**Issue by d4ivc** [FullStackEggDRoa/proyecto_003-GF#128]
Tanto en cliente como en proveedor en el formulario de registro se solicita ingresar una imagen que **no** debería estar.
Recuerdo que la imagen sólo se solicita en el formulario de actualizar los datos (mi perfil).
Y cuando se registra con éxito el mensaje aparece en rojo.

También en el formulario Proveedor figura "Profesión" y "Categoría servicio" donde sólo debería figurar la categoría de servicio con el menú desplegable.

**Comment by LucasGes** [comment]
Se corrige registro cliente/proveedor
Se modifica el alert de éxito a color verde.

Resta: quitar el input de profesion.

**Comment by dnroar** [comment]
De acuerdo a lo que @LucasGes muestra debe estar uno u otro en este ámbito se aconseja usar el Select para ya normalizar el ingreso de esta data. Lo cual haría durante la edición recuperar de forma coherente esta data durante la modificación.

```
  <!--  input viejo de categoria servicio-->
                <div class="inputContainer">
                    <input type="text" class="input" placeholder="" name="categoriaServicio" th:value="${categoriaServicio}" required>
                    <label for="" class="label">Profesión</label>
                </div>
                
                <div class="inputContainer">
                    <select class="form-select input" aria-label="Default select example">
                        <option selected>Categoria de servicio</option>
                        <option value="Carpintería">Carpintería</option>
                        <option value="Gas">Gas</option>
                        <option value="Electricidad">Electricidad</option>
                        <option value="Plomería">Plomería</option>
                        <option value="Jardinería">Jardinería</option>
                        <option value="Construcción">Construcción</option>
                    </select>
                </div>
```

**Comment by DaiColqui** [comment]
Ready.
