### ISSUE TITLE
No se puede cargar la Imagen de un Proveedor - FrontEnd/BackEnd

### ISSUE THREAD

**Issue by dnroar** [FullStackEggDRoa/proyecto_003-GF#140]
Durante la actualización de datos de un Proveedor, se puede incluir toda la data excepto por la categoría, ya que da un error, y da un Crash durante la grabación de la data.

Aparentemente esta guardando la información de imagen en la base de datos, pero durante la carga de la sesión la imagen del avatar no se carga.

**Comment by dnroar** [comment]
@Dai te comento que con este aporte todavía la imagen del avatar no se carga. Esto para tu conocimiento.

**Comment by DaiColqui** [comment]
Ready 🤙🏽
