### ISSUE TITLE
Botones de Manejo de Perfil Administrador - FrontEnd

### ISSUE THREAD

**Issue by dnroar** [FullStackEggDRoa/proyecto_003-GF#141]
No funciona el botón de cerrar sesión.

![Screen Shot 2023-09-24 at 10 07 39](https://github.com/FullStackEggDRoa/proyecto_003-GF/assets/119772142/50c763b3-6c4e-40cd-a569-7758efea79b2)

**Comment by AzulCastroviejo** [comment]
Resuelto faltaba el href="/salir"

**Comment by dnroar** [comment]
Gracias..
