### ISSUE TITLE
Avatar Deformado en NavBar Sesion Cliente - FrontEnd

### ISSUE THREAD

**Issue by dnroar** [FullStackEggDRoa/proyecto_003-GF#142]
Se encuentra deformado la presentación del Avatar de la Sesión Cliente.

![Screen Shot 2023-09-24 at 10 10 27](https://github.com/FullStackEggDRoa/proyecto_003-GF/assets/119772142/51272b66-a29a-4da7-a5ca-2a82a11213c8)

**Comment by dnroar** [comment]
Al parecer este issue ya se encuentra resuelto. @AzulCastroviejo @d4ivc y @MoniFerVivas ?

**Comment by DaiColqui** [comment]
Así es.
