### ISSUE TITLE
Normalizar Mejores en Formulario Modificar Cliente.

### ISSUE THREAD

**Issue by dnroar** [FullStackEggDRoa/proyecto_003-GF#167]
No se muestra el mismo tratamiento de los otros formularios en el formulario modificar Cliente.

![Screen Shot 2023-09-28 at 17 28 44](https://github.com/FullStackEggDRoa/proyecto_003-GF/assets/119772142/bf4793d5-e6d2-4445-b15e-025a9c4db915)

**Comment by armandie2013** [comment]
Corregido en ambos formularios.
![Sin título](https://github.com/FullStackEggDRoa/proyecto_003-GF/assets/108833184/163fada6-e178-4469-ba2e-f68ffa085a02)
