### ISSUE TITLE
Letrero DashBoard Cliente

### ISSUE THREAD

**Issue by dnroar** [FullStackEggDRoa/proyecto_003-GF#168]
El titulo del Dash, se podría usar el mismo como el de Administrador Ej. DashBoard Cliente y para proveedor Dash Proveedor

![Screen Shot 2023-09-28 at 17 48 10](https://github.com/FullStackEggDRoa/proyecto_003-GF/assets/119772142/a10d12a4-579b-45ca-aaf4-61a06606cf53)

**Comment by DaiColqui** [comment]
El título del dash se habló que quedaba Sesión cliente/proveedor. También ya está solucionado para que aparezca un solo título.
