### ISSUE TITLE
Icono - Home en Pagina Inicio / Sesion Admin

### ISSUE THREAD

**Issue by dnroar** [FullStackEggDRoa/proyecto_003-GF#177]
Luego de la carga de un aporte de @armandie2013 y @LucasGes , este icono dejo de cargarse. Por favor revisar el src del mismo.

![Screen Shot 2023-09-29 at 20 17 31](https://github.com/FullStackEggDRoa/proyecto_003-GF/assets/119772142/60ffd693-201b-4fcb-b58e-29350fd23b73)

Al parecer tambien ocurren en la pagina de Sesion Admin:

![Screen Shot 2023-09-29 at 20 51 39](https://github.com/FullStackEggDRoa/proyecto_003-GF/assets/119772142/efb006fa-fb98-440f-99ac-f96dfa2b41ed)

**Comment by armandie2013** [comment]
Corregido.

**Comment by dnroar** [comment]
@armandie2013 Diego podrías enviarnos indicaciones, de lo contrario un pullrequest con el cambio?

**Comment by armandie2013** [comment]
Envie un pullrequest con los cambio correspondientes y demas correcciones

**Comment by dnroar** [comment]
Perfecto. Gracias PullRequest #178 ya esta fusionado.
