### ISSUE TITLE
Carta Perfil Proveedor - Sesion Proveedor

### ISSUE THREAD

**Issue by dnroar** [FullStackEggDRoa/proyecto_003-GF#206]
En caso de tener tiempo disponible mejorar el maquetado de esta vista.

![Screen Shot 2023-10-04 at 12 53 05](https://github.com/FullStackEggDRoa/proyecto_003-GF/assets/119772142/1725051f-c799-4b9c-9fdd-14587dc147c9)

**Comment by LucasGes** [comment]
Se adecua el tamaño de la imagen al contenedor.
