### ISSUE TITLE
Registro de Usuario Bug - BackEnd

### ISSUE THREAD

**Issue by dnroar** [FullStackEggDRoa/proyecto_003-GF#33]
Existe algo en Servicio registrarCliente(), el cual levanta una excepción. @d4ivc (Dai) por favor verificar que estaría ocurriendo. Ya que pese a que se ingresan todos los datos de usuario de forma correcta, se levanta una excepción.

https://github.com/FullStackEggDRoa/proyecto_003-GF/blob/2ea15300f9d4a33979db74a7f0e1b7f2fd65b555/src/main/java/GrupoF/Proyecto3/Controladores/controladorInicio.java#L86C13-L86C13

**Comment by dnroar** [comment]
Después de la revisión de este Bug o Incidencia, se concluye que el inconveniente de la grabación del registre, infiere directamente en la clase registrarCliente, cuya colaborador a cargo es @d4ivc .

El bug se genera principalmente ya que durante la creación del Objeto DNI, no se lo graba en la base de datos. Razón por la cual JPA, no permite grabar el objeto de Cliente debido a que no existe un respaldo de dicho objeto en la base de datos.

Pasos a reproducir para solventar el inconveniente:

1. Crear un enlace al repositorio DniRepositorio, que hace falta generarlo como atributo en el servicio en mención:  
 ```
@Autowired
private DniRepositorio dR;
```
2. Seguidamente, justo después de almacenar el dato de DNI, se debe invocar el método del repositorio save:
 ```
dR.save(dni1);
```
Por otro lado, se recomendaría usar un mejor llamado de la función varlidarC. Con el objetivo de mejorar las prácticas de cleanCode.

Ej. validarDatosCliente o validarDatos.

Cualquier novedad no duden comunicarlas.

**Comment by d4ivc** [comment]
Dani, hice los cambios recomendados y me sigue sin funcionar.

**Comment by dnroar** [comment]
Listo Dai. Como habíamos observado y trabajado este bug juntos, al parecer ya esta corregido. El problema de que luego de tener todas las correcciones, no puedas registrar tu usuario, es probablemente debido a que tu boot spring se haya corrompido. Habriremos otro caso para monitorear ese Bug...
