### ISSUE TITLE
Validación de Data en Login - FrontEnd

### ISSUE THREAD

**Issue by dnroar** [FullStackEggDRoa/proyecto_003-GF#34]
No se muestra información de validación de datos de login en el form. Ej. Usuario no resgistrado, campo vacio, mal ingreso de correo, etc.

https://github.com/FullStackEggDRoa/proyecto_003-GF/blob/3547491377833c5e0cafe1632f9484e4be85e840/src/main/resources/templates/login.html#L41C8-L41C8

@d4ivc y @AzulCastroviejo revisar por fa..

**Comment by AzulCastroviejo** [comment]
Ahora  lo reviso , creia que venia con el merge. Verifico y arreglo

**Comment by AzulCastroviejo** [comment]
Revision en mi developer y esta el alert , no se debe haber hecho bien el pull
