### ISSUE TITLE
Usar Clase Excepción Propietaria - BackEnd

### ISSUE THREAD

**Issue by dnroar** [FullStackEggDRoa/proyecto_003-GF#39]
Debido al aporte realizado por @ENRI644 que consiste en la elaboración de la clase propia de excepciones; es necesario que todos las implementemos.

Por el momento me he fijado, que el colaborador que más ha usado excepciones es @d4ivc por lo que tendría usar las de implementadas por @ENRI644 .

Cualquier novedad no duden en comunicar.

**Comment by d4ivc** [comment]
Implementada 👍

**Comment by d4ivc** [comment]
cerrada
