### ISSUE TITLE
Implementación de Mensajes para Formularios - FrontEnd

### ISSUE THREAD

**Issue by dnroar** [FullStackEggDRoa/proyecto_003-GF#40]
Por favor recordar al equipo de FrontEnd, mostrar los mensajes en formularios de ingreso y registro, que ya estan implementados en controladores, respecto a:

- Existencia o no de un usuario.
- Requisito mínimo de creación de contraseña.
- Validación de ingreso correcto de correo electrónico.
- entre otras.

Cualquier novedad no duden en comunicar.

**Comment by DaiColqui** [comment]
Listo!
