### ISSUE TITLE
Revisión de metodo registrarProveedor - BackEnd

### ISSUE THREAD

**Issue by dnroar** [FullStackEggDRoa/proyecto_003-GF#51]
Luego de la subida de los aportes de ENRI. Aparece un bug con el metodo de servicio registrarProveedor. @d4ivc por favor tu ayuda con esta incidencia.

ENRI advirtio de este posible bug, necesitamos tu ayuda con el mismo. Revisamos juntos si estas de acuerdo.

**Comment by d4ivc** [comment]
Logrado <:o)
