### ISSUE TITLE
Modificación de Contraseña Clientes/Proveedores- FrontEnd

### ISSUE THREAD

**Issue by dnroar** [FullStackEggDRoa/proyecto_003-GF#83]
Respecto a la integración del Codigo para la presentación del Sprint #2, se detecta que en el formulario de modificación de Cliente y Proveedor, se pretende usar la contraseña guardada en la base datos.

Recordemos, que esta contraseña esta encriptada, si la recuperamos con: `th:text="${Cliente.contrasenia}"`; estariamos obteniendo la cadena de texto ya con el hash aplicado, si grabamos así, estaríamos guardando una contraseña distinta a la original. @AzulCastroviejo buscar alternativas para que esto no ocurra: Ej. Configurar un Placeholder que diga, escribe tu nueva contraseña.

Cualquier comentario no duden en comunicar.

**Comment by AzulCastroviejo** [comment]
Borramos el campo modificacion de contraseña por esta semana

**Comment by dnroar** [comment]
Con las modifiaciones realizadas, este Issue ya se encuentra resuelto. Se observa en los formularios y validaciones de backEnd, que se valida la contraseña de forma adecuada.
