### ISSUE TITLE
Agregar enum NombreEstadoContrato "CANCELADO" - BackEnd

### ISSUE THREAD

**Issue by d4ivc** [FullStackEggDRoa/proyecto_003-GF#99]
Teniendo en cuenta el PDF del proyecto en "Casos de uso" el cliente puede **cancelar** el contrato cuando solicita el servicio y también una vez aceptado por el proveedor.
No es lo mismo que rechazado ya que la opción de rechazar en propia del proveedor.
Los estados del contrato entonces serían: ESPERA, CANCELADO, RECHAZADO, PROCESO y FINALIZADO.

En conclusión hay que agregar CANCELADO en el enum NombreEstadoContrato.

**Comment by dnroar** [comment]
De acuerdo a indicaciones por @d4ivc, se procede a realizar cambios en el enumerador de estados de Contrato. Ya se encuentra este cambio incluido como un estable, en la rama #developer.

Cualquier comentario no duden en comunicar.
